import { AgencyMeta, AgencyType, IndustryRulePreset } from '../types/permit';

export const AGENCY_METADATA: Record<AgencyType, AgencyMeta> = {
  ZONING_PLANNING: {
    id: 'ZONING_PLANNING',
    name: 'City Planning & Zoning Commission',
    shortName: 'Zoning & Planning',
    code: 'CPZC',
    department: 'Urban Land Use & Spatial Development',
    badgeColor: 'blue',
    statutoryDays: 14,
  },
  BUILDING_SAFETY: {
    id: 'BUILDING_SAFETY',
    name: 'Department of Buildings & Structural Safety',
    shortName: 'Buildings (DOB)',
    code: 'DOB',
    department: 'Engineering & Construction Bureau',
    badgeColor: 'indigo',
    statutoryDays: 21,
  },
  FIRE_MARSHAL: {
    id: 'FIRE_MARSHAL',
    name: 'Bureau of Fire Prevention & Life Safety',
    shortName: 'Fire Prevention',
    code: 'BFPS',
    department: 'Municipal Fire Protection Authority',
    badgeColor: 'amber',
    statutoryDays: 15,
  },
  PUBLIC_HEALTH: {
    id: 'PUBLIC_HEALTH',
    name: 'Department of Public Health & Food Sanitation',
    shortName: 'Public Health',
    code: 'DPH',
    department: 'Environmental Health & Hygiene',
    badgeColor: 'emerald',
    statutoryDays: 18,
  },
  ENVIRONMENTAL: {
    id: 'ENVIRONMENTAL',
    name: 'Environmental Protection & Pollution Control',
    shortName: 'Environmental (EPA)',
    code: 'EPPC',
    department: 'Clean Air, Water & Waste Management',
    badgeColor: 'teal',
    statutoryDays: 25,
  },
  COMMERCE_LABOR: {
    id: 'COMMERCE_LABOR',
    name: 'Department of Commerce & Labor Standards',
    shortName: 'Commerce & Labor',
    code: 'DCLS',
    department: 'Trade Licensing & Workforce Regulatory',
    badgeColor: 'violet',
    statutoryDays: 10,
  },
};

export const INDUSTRY_PRESETS: IndustryRulePreset[] = [
  {
    category: 'food_hospitality',
    label: 'Food & Beverage / Hospitality',
    description: 'Bakeries, cafes, full-service dining, brewpubs, cloud kitchens, and catering.',
    typicalAgencies: ['ZONING_PLANNING', 'BUILDING_SAFETY', 'FIRE_MARSHAL', 'PUBLIC_HEALTH', 'COMMERCE_LABOR'],
    averageTimelineDays: 24,
    estimatedFeeRange: '$1,450 – $2,800',
    mandatoryDocs: [
      'Commercial Kitchen Mechanical Exhaust Plan',
      'Food Safety Manager Certification (ServSafe)',
      'Plumbing Grease Interceptor Schematics',
      'Fire Suppression System Inspection Record',
      'Floor Plan with Occupant Load Calculations',
    ],
  },
  {
    category: 'biotech_healthcare',
    label: 'Biotech, Life Sciences & Clinics',
    description: 'Medical laboratories, diagnostic centers, clinical research, outpatient facilities.',
    typicalAgencies: ['ZONING_PLANNING', 'BUILDING_SAFETY', 'FIRE_MARSHAL', 'ENVIRONMENTAL', 'COMMERCE_LABOR'],
    averageTimelineDays: 32,
    estimatedFeeRange: '$3,200 – $5,500',
    mandatoryDocs: [
      'Biohazard & Hazardous Waste Disposal Protocol',
      'HVAC HEPA Negative Pressure Certification',
      'Emergency Chemical Spill Containment Plan',
      'State Medical Board Facility Registration',
      'Radiation Safety Officer Designation (if applicable)',
    ],
  },
  {
    category: 'industrial_manufacturing',
    label: 'Light Manufacturing & Assembly',
    description: 'Precision machining, electronics assembly, craft brewing, textile manufacturing.',
    typicalAgencies: ['ZONING_PLANNING', 'BUILDING_SAFETY', 'FIRE_MARSHAL', 'ENVIRONMENTAL', 'COMMERCE_LABOR'],
    averageTimelineDays: 28,
    estimatedFeeRange: '$2,800 – $4,600',
    mandatoryDocs: [
      'Industrial Waste Effluent Discharge Plan',
      'Machine Guarding & OSHA Compliance Strategy',
      'Structural Floor Load Engineering Report',
      'Hazardous Material Inventory Statement (HMIS)',
      'Acoustic Vibration & Noise Emission Study',
    ],
  },
  {
    category: 'retail_commercial',
    label: 'Retail & Commercial Services',
    description: 'Boutique stores, specialty supermarkets, showrooms, wellness & fitness studios.',
    typicalAgencies: ['ZONING_PLANNING', 'BUILDING_SAFETY', 'FIRE_MARSHAL', 'COMMERCE_LABOR'],
    averageTimelineDays: 16,
    estimatedFeeRange: '$850 – $1,600',
    mandatoryDocs: [
      'ADA Accessibility & Egress Blueprint',
      'Commercial Lease Agreement with Landlord Consent',
      'Storefront Signage & Exterior Elevation Drawing',
      'Fire Extinguisher Placement Layout',
    ],
  },
  {
    category: 'technology_coworking',
    label: 'Technology Offices & Coworking',
    description: 'Software development centers, incubator hubs, shared creative workspaces.',
    typicalAgencies: ['ZONING_PLANNING', 'BUILDING_SAFETY', 'FIRE_MARSHAL', 'COMMERCE_LABOR'],
    averageTimelineDays: 14,
    estimatedFeeRange: '$750 – $1,400',
    mandatoryDocs: [
      'Architectural Layout with Exit Capacities',
      'Electrical Load Certificate for Server Equipment',
      'Emergency Evacuation Routing Diagram',
      'Certificate of Good Standing (Secretary of State)',
    ],
  },
  {
    category: 'education_childcare',
    label: 'Education & Child Care Facilities',
    description: 'Early learning centers, daycares, vocational schools, tutoring academies.',
    typicalAgencies: ['ZONING_PLANNING', 'BUILDING_SAFETY', 'FIRE_MARSHAL', 'PUBLIC_HEALTH', 'COMMERCE_LABOR'],
    averageTimelineDays: 30,
    estimatedFeeRange: '$2,100 – $3,900',
    mandatoryDocs: [
      'State Child Welfare Licensing Clearance',
      'Lead & Asbestos Environmental Clearance',
      'Outdoor Playground Fencing & Impact Surface Specs',
      'Staff Background Check Verification Register',
      'Pediatric CPR & Emergency Preparedness Protocol',
    ],
  },
];
